### PR TITLE
feat: :sparkles: probes capabilites for cloud run

### PR DESCRIPTION
**Pull request by rs1986x**
Hi! I spent some time adding dynamic blocks for liveness and readiness probes with optional blocks. I hope you like it

### CODE REVIEW

**Comment by rs1986x** [comment]
Hi - what does `Needs /gcbrun from a collaborator` means?

**Comment by rs1986x** [comment]
what did i do wrong? i am using the code i submitted and it works fine, do i need to modify something in the tests?

**Comment by apeabody** [comment]
> what did i do wrong? i am using the code i submitted and it works fine, do i need to modify something in the tests?

Hi @rs1986x - The failed check status can also mean a maintainer to trigger the INT and LINT CI.  Unfortunately this needs to happen after each new commit.  I just triggered so they are running now.

**Comment by rs1986x** [comment]
Thanks @apeabody, fixed the trailining spaces, ran the lint and it seems to pass to pass all the checks except for a `Error: Failed to install provider from shared cache` for the terraform google-beta provider

**Comment by prabhu34** [comment]
@rs1986x Thanks for contributing and adding the probes (which are still beta).
Can we have an simple example and test case created along with this change?

**Comment by rs1986x** [comment]
> @rs1986x Thanks for contributing and adding the probes (which are still beta). Can we have an simple example and test case created along with this change?

Hi @prabhu34 - i can for sure write an example no problem, i don't know if i have enough skills to write the test case though, I am not a golang developer, do not have experience writing tests with kitchen. I can try but it would be nice to get a few pointers

**Comment by Klaitos** [comment]
up, would be nice to use probes :)

**Comment by andrewmackett** [comment]
This would be a great feature to have. Is there anything I can do to help get this PR reviewed and merged? It appears as though it just needs to be brought up to date with the `main` branch.

**Review by gtsorbo — APPROVED** [review]

**Comment by andrewmackett** [comment]
Thank you @apeabody @gtsorbo! Appreciate you looking at this. 🙌🏻

**Comment by gtsorbo** [comment]
@thomasnoppe since this PR is already merged, feel free to propose the change in a new PR and we can review!

**Pull request merged**
