### PR TITLE
feat(probes): Add support for startup and liveness probes

### PR DESCRIPTION
**Pull request by cyberbliss**
Hi

This PR is to enable startup and liveness probes to be specified. Open to suggestions if folks feel there is more I should include in this PR.

### CODE REVIEW

**Comment by cyberbliss** [comment]
> Possible duplicates #101 and #120

Ah, my bad. I hadn't seen #101. Both PRs are very similar so it would be good to get one of them approved and merged. What is required to make that happen?

**Comment by andrewmackett** [comment]
This would be a great feature to have. Is there anything I can do to help get this PR reviewed and merged? It appears as though it just needs to be brought up to date with the `main` branch.

**Comment by andrewmackett** [comment]
Please may this be updated with the `main` branch so that it could be reviewed and merged?
@cyberbliss @prabhu34 @gtsorbo

**Comment by cyberbliss** [comment]
Sadly I think it would be a waste of my time. The maintainers seem.... unenthusiastic about dealing with PRs from external parties

**Comment by gtsorbo** [comment]
Duplicate to #101

**Comment by andrewmackett** [comment]
I appreciate maintaining a public repo isn't easy, so just wanted to say thank you @gtsorbo.

**Pull request closed without merging**
